// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "forge-std/Test.sol";
import "@openzeppelin/contracts/governance/TimelockController.sol";
import "@openzeppelin/contracts/proxy/ERC1967/ERC1967Proxy.sol";
import "../src/AllowlistGatedUpgradeable.sol";
import "../src/Blocklist.sol";
import "../src/CustodianRegistry.sol";
import "../src/DelegatingVestingWallet.sol";
import "../src/FORAGETreasury.sol";
import "../src/ForageGovernor.sol";
import "../src/ForageToken.sol";
import "../src/GuardianModule.sol";
import "../src/RISKUSD.sol";
import "../src/RISKUSDVault.sol";
import "../src/StakingQueue.sol";
import "../src/USDCTreasury.sol";
import "../src/VaultRegistry.sol";
import "../src/atRISKUSD.sol";
import "../src/hyperliquid/HLTradingBridge.sol";
import "../src/interfaces/IAllowlist.sol";
import "../src/modules/RISKUSDVaultModule.sol";
import "../src/modules/StakingQueueModule.sol";
import "./helpers/AllowlistHarness.sol";
import "./helpers/AllowlistTestBase.sol";
import "./mocks/MockSequencerUptimeFeed.sol";
import "./mocks/MockUSDC.sol";

/// @dev GENERATED by contracts/script/gen_selector_sweep.py --write; every non-view, non-pure function of the
/// fourteen gated contracts is called from one unverified EOA and checked against the real Allowlist registry.
contract GateSweepTest is Test, AllowlistTestBase {
    uint8 internal constant CONTRACTS = 14;
    uint256 internal constant ROWS = 386;
    uint256 internal constant EXEMPT_PAIRS = 9;
    uint256 internal constant GATED_PAIRS = 347;
    uint256 internal constant SEAM_PAIRS = 30;
    uint8 internal constant SELECTOR_KINDS = 3;
    uint8 internal constant KIND_GATED = 0;
    uint8 internal constant KIND_EXEMPT = 1;
    uint8 internal constant KIND_SEAM = 2;

    struct SweepPair {
        uint8 target;
        uint8 kind;
        bytes4 selector;
        bytes data;
    }

    MockUSDC internal sweepUsdc;
    MockSequencerUptimeFeed internal sweepFeed;
    TimelockController internal sweepTimelock;
    RISKUSD internal sweepRiskusd;
    RISKUSDVault internal sweepVault;
    VaultRegistry internal sweepVaultRegistry;
    FORAGETreasury internal sweepForageTreasury;
    ForageToken internal sweepForage;
    StakingQueue internal sweepQueue;
    ForageGovernor internal sweepGovernor;
    GuardianModule internal sweepGuardianModule;
    Blocklist internal sweepBlocklist;
    CustodianRegistry internal sweepCustodianRegistry;
    USDCTreasury internal sweepUsdcTreasury;
    HLTradingBridge internal sweepBridge;
    DelegatingVestingWallet internal sweepVestingWallet;
    atRISKUSD[4] internal sweepTierVaults;
    address internal sweepUnverified;

    function setUp() public {
        vm.chainId(31_337);
        vm.warp(100);
        sweepUnverified = makeAddr("unverified");
        _deploySweepRegistry();
        _deploySweepStack();
        _wireSweepGate();
        _requireSweepWiring();
    }

    function _deploySweepRegistry() internal {
        address[] memory systemAccounts = new address[](1);
        systemAccounts[0] = address(this);
        address[] memory actors = new address[](0);
        deployAllowlistHarness(systemAccounts, actors);
    }

    function _deploySweepStack() internal {
        sweepUsdc = new MockUSDC();
        sweepFeed = new MockSequencerUptimeFeed();
        address[] memory proposers = new address[](1);
        proposers[0] = address(this);
        sweepTimelock = new TimelockController(0, proposers, proposers, address(this));
        sweepRiskusd = RISKUSD(_proxy(address(new RISKUSD()), abi.encodeCall(RISKUSD.initialize, (address(this)))));
        sweepVault = RISKUSDVault(
            _proxy(
                address(new RISKUSDVault()),
                abi.encodeCall(RISKUSDVault.initialize, (address(sweepUsdc), address(sweepRiskusd), address(this)))
            )
        );
        sweepVault.setVaultModule(address(new RISKUSDVaultModule()));
        sweepVaultRegistry = VaultRegistry(
            _proxy(address(new VaultRegistry()), abi.encodeCall(VaultRegistry.initialize, (address(this))))
        );
        for (uint256 i; i < 4; ++i) {
            sweepTierVaults[i] = atRISKUSD(
                _proxy(
                    address(new atRISKUSD()),
                    abi.encodeCall(
                        atRISKUSD.initialize,
                        (
                            address(sweepRiskusd),
                            address(0),
                            address(0),
                            1 days,
                            1 hours,
                            uint8(i),
                            "atRISKUSD",
                            address(this)
                        )
                    )
                )
            );
        }
        uint256 nonce = vm.getNonce(address(this));
        sweepForageTreasury = FORAGETreasury(
            _proxy(
                address(new FORAGETreasury()),
                abi.encodeCall(FORAGETreasury.initialize, (vm.computeCreateAddress(address(this), nonce + 3), address(this)))
            )
        );
        sweepForage = ForageToken(
            _proxy(
                address(new ForageToken()),
                abi.encodeCall(ForageToken.initialize, (address(this), address(sweepForageTreasury), address(this)))
            )
        );
        address[4] memory tiers = [
            address(sweepTierVaults[0]),
            address(sweepTierVaults[1]),
            address(sweepTierVaults[2]),
            address(sweepTierVaults[3])
        ];
        sweepQueue = StakingQueue(
            _proxy(
                address(new StakingQueue()),
                abi.encodeCall(
                    StakingQueue.initialize,
                    (address(sweepRiskusd), address(sweepForage), tiers, address(sweepVaultRegistry), address(this))
                )
            )
        );
        sweepQueue.setQueueModule(address(new StakingQueueModule()));
        nonce = vm.getNonce(address(this));
        address[] memory guardians = new address[](0);
        uint256[] memory permissions = new uint256[](0);
        sweepGuardianModule = GuardianModule(
            _proxy(
                address(new GuardianModule()),
                abi.encodeCall(
                    GuardianModule.initialize,
                    (vm.computeCreateAddress(address(this), nonce + 3), address(sweepTimelock), guardians, permissions)
                )
            )
        );
        sweepGovernor = ForageGovernor(
            payable(
                _proxy(
                    address(new ForageGovernor()),
                    abi.encodeCall(
                        ForageGovernor.initialize,
                        (
                            address(sweepForage),
                            address(sweepTimelock),
                            uint48(0),
                            uint32(1 hours),
                            uint256(100),
                            uint256(400),
                            address(sweepGuardianModule)
                        )
                    )
                )
            )
        );
        sweepUsdcTreasury = USDCTreasury(
            _proxy(
                address(new USDCTreasury()),
                abi.encodeCall(
                    USDCTreasury.initialize,
                    (
                        address(sweepUsdc),
                        address(sweepVault),
                        address(sweepVaultRegistry),
                        address(this),
                        makeAddr("foundation primary"),
                        makeAddr("foundation backup"),
                        makeAddr("protocol primary"),
                        makeAddr("protocol backup")
                    )
                )
            )
        );
        sweepCustodianRegistry = CustodianRegistry(
            _proxy(
                address(new CustodianRegistry()),
                abi.encodeCall(
                    CustodianRegistry.initialize,
                    (address(this), address(sweepGovernor), address(sweepGuardianModule))
                )
            )
        );
        HLTradingBridge.RouteConfig memory route = HLTradingBridge.RouteConfig(
            makeAddr("cold account"),
            bytes32(uint256(uint160(makeAddr("cold account")))),
            uint64(block.chainid),
            address(sweepFeed)
        );
        sweepBridge = HLTradingBridge(
            _proxy(
                address(new HLTradingBridge()),
                abi.encodeCall(
                    HLTradingBridge.initialize,
                    (
                        address(sweepUsdc),
                        address(sweepVault),
                        address(sweepUsdcTreasury),
                        address(sweepCustodianRegistry),
                        address(this),
                        makeAddr("keeper"),
                        makeAddr("custodian executor"),
                        address(sweepGuardianModule),
                        route
                    )
                )
            )
        );
        sweepBlocklist = Blocklist(
            _proxy(address(new Blocklist()), abi.encodeCall(Blocklist.initialize, (address(this), address(this))))
        );
        sweepVestingWallet = new DelegatingVestingWallet(
            address(this), uint64(block.timestamp), uint64(4 * 365 days), uint64(365 days), address(this), address(allowlist)
        );
    }

    function _proxy(address implementation, bytes memory initData) internal returns (address) {
        return address(new ERC1967Proxy(implementation, initData));
    }

    function _wireSweepGate() internal {
        address[CONTRACTS] memory targets = _sweepTargets();
        for (uint256 i; i < CONTRACTS; ++i) {
            allowlist.setSystemAccount(targets[i], true);
        }
        allowlist.setSystemAccount(address(sweepTimelock), true);
        for (uint256 i; i < CONTRACTS; ++i) {
            if (targets[i] != address(sweepGovernor) && targets[i] != address(sweepGuardianModule)) {
                IAllowlistSettable(targets[i]).setAllowlist(address(allowlist));
            }
        }
        _timelockSetAllowlist(address(sweepGuardianModule));
        _timelockSetAllowlist(address(sweepGovernor));
    }

    function _timelockSetAllowlist(address target) internal {
        bytes memory data = abi.encodeCall(IAllowlistSettable.setAllowlist, (address(allowlist)));
        sweepTimelock.schedule(target, 0, data, bytes32(0), bytes32(0), 0);
        sweepTimelock.execute(target, 0, data, bytes32(0), bytes32(0));
    }

    function _requireSweepWiring() internal view {
        address[CONTRACTS] memory targets = _sweepTargets();
        for (uint256 i; i < CONTRACTS; ++i) {
            assertGt(targets[i].code.length, 0, "SWEEP target has no code");
            assertEq(
                AllowlistGatedUpgradeable(targets[i]).allowlist(),
                address(allowlist),
                "SWEEP target is not wired to the real registry"
            );
        }
    }

    function _sweepTargets() internal view returns (address[CONTRACTS] memory targets) {
        targets[0] = address(sweepTierVaults[0]);
        targets[1] = address(sweepBlocklist);
        targets[2] = address(sweepCustodianRegistry);
        targets[3] = address(sweepVestingWallet);
        targets[4] = address(sweepForageTreasury);
        targets[5] = address(sweepGovernor);
        targets[6] = address(sweepForage);
        targets[7] = address(sweepGuardianModule);
        targets[8] = address(sweepBridge);
        targets[9] = address(sweepRiskusd);
        targets[10] = address(sweepVault);
        targets[11] = address(sweepQueue);
        targets[12] = address(sweepUsdcTreasury);
        targets[13] = address(sweepVaultRegistry);
    }

    function _sweepPairs() internal pure returns (SweepPair[] memory pairs) {
        pairs = new SweepPair[](ROWS);
        pairs[0] = SweepPair(1, KIND_GATED, 0x1b30bb25, abi.encodeWithSelector(0x1b30bb25, address(0)));
        pairs[1] = SweepPair(1, KIND_GATED, 0x2161f278, abi.encodeWithSelector(0x2161f278, address(0)));
        pairs[2] = SweepPair(1, KIND_SEAM, 0x485cc955, abi.encodeWithSelector(0x485cc955, address(0), address(0)));
        pairs[3] = SweepPair(1, KIND_GATED, 0x4f1ef286, abi.encodeWithSelector(0x4f1ef286, address(0), ""));
        pairs[4] = SweepPair(1, KIND_SEAM, 0x58bf3c7f, abi.encodeWithSelector(0x58bf3c7f, address(0)));
        pairs[5] = SweepPair(
            1, KIND_GATED, 0x7487e389, abi.encodeWithSelector(
                0x7487e389, address(0), uint256(0), uint256(0)
            )
        );
        pairs[6] = SweepPair(1, KIND_GATED, 0x79ba5097, abi.encodeWithSelector(0x79ba5097));
        pairs[7] = SweepPair(1, KIND_GATED, 0xad2bb1b3, abi.encodeWithSelector(0xad2bb1b3, address(0)));
        pairs[8] = SweepPair(1, KIND_GATED, 0xc304555f, abi.encodeWithSelector(0xc304555f, address(0)));
        pairs[9] = SweepPair(1, KIND_GATED, 0xc5e07122, abi.encodeWithSelector(0xc5e07122));
        pairs[10] = SweepPair(1, KIND_GATED, 0xce0f213c, abi.encodeWithSelector(0xce0f213c, address(0)));
        pairs[11] = SweepPair(1, KIND_GATED, 0xec6a1a20, abi.encodeWithSelector(0xec6a1a20));
        pairs[12] = SweepPair(1, KIND_GATED, 0xf2fde38b, abi.encodeWithSelector(0xf2fde38b, address(0)));
        pairs[13] = SweepPair(2, KIND_GATED, 0x05ff9232, abi.encodeWithSelector(0x05ff9232, bytes32(0), uint256(0)));
        pairs[14] = SweepPair(
            2, KIND_GATED, 0x07309e84, abi.encodeWithSelector(
                0x07309e84, CustodianRegistry.CustodianConfig(bytes32(0), CustodianRegistry.CustodianKind(0), address(0), address(0), uint32(0), bytes32(0), uint256(0), uint256(0), uint256(0), uint16(0), uint16(0), uint16(0))
            )
        );
        pairs[15] = SweepPair(2, KIND_GATED, 0x0da417e9, abi.encodeWithSelector(0x0da417e9, bytes32(0), false));
        pairs[16] = SweepPair(
            2, KIND_GATED, 0x17c66c94, abi.encodeWithSelector(
                0x17c66c94, bytes32(0), bytes32(0), address(0)
            )
        );
        pairs[17] = SweepPair(2, KIND_GATED, 0x2776ced5, abi.encodeWithSelector(0x2776ced5, bytes32(0), bytes32(0)));
        pairs[18] = SweepPair(
            2, KIND_GATED, 0x2bb14a06, abi.encodeWithSelector(
                0x2bb14a06, bytes32(0), bytes32(0), false
            )
        );
        pairs[19] = SweepPair(2, KIND_GATED, 0x3f4ba83a, abi.encodeWithSelector(0x3f4ba83a));
        pairs[20] = SweepPair(2, KIND_GATED, 0x43976aeb, abi.encodeWithSelector(0x43976aeb, bytes32(0), uint256(0)));
        pairs[21] = SweepPair(2, KIND_GATED, 0x4b572303, abi.encodeWithSelector(0x4b572303, address(0)));
        pairs[22] = SweepPair(2, KIND_GATED, 0x4f1ef286, abi.encodeWithSelector(0x4f1ef286, address(0), ""));
        pairs[23] = SweepPair(2, KIND_SEAM, 0x58bf3c7f, abi.encodeWithSelector(0x58bf3c7f, address(0)));
        pairs[24] = SweepPair(2, KIND_GATED, 0x5d2ee5cf, abi.encodeWithSelector(0x5d2ee5cf, bytes32(0), uint256(0)));
        pairs[25] = SweepPair(2, KIND_GATED, 0x60d311fc, abi.encodeWithSelector(0x60d311fc, bytes32(0)));
        pairs[26] = SweepPair(2, KIND_GATED, 0x63d4dddb, abi.encodeWithSelector(0x63d4dddb, bytes32(0), bytes32(0)));
        pairs[27] = SweepPair(
            2, KIND_GATED, 0x6c8a88db, abi.encodeWithSelector(
                0x6c8a88db, bytes32(0), bytes32(0), address(0)
            )
        );
        pairs[28] = SweepPair(2, KIND_GATED, 0x79ba5097, abi.encodeWithSelector(0x79ba5097));
        pairs[29] = SweepPair(
            2, KIND_GATED, 0x7ff4f2cd, abi.encodeWithSelector(
                0x7ff4f2cd, bytes32(0), bytes32(0), address(0)
            )
        );
        pairs[30] = SweepPair(2, KIND_GATED, 0x8456cb59, abi.encodeWithSelector(0x8456cb59));
        pairs[31] = SweepPair(2, KIND_GATED, 0x9518f64a, abi.encodeWithSelector(0x9518f64a, address(0)));
        pairs[32] = SweepPair(2, KIND_GATED, 0x9b73b121, abi.encodeWithSelector(0x9b73b121, bytes32(0), bytes32(0)));
        pairs[33] = SweepPair(
            2, KIND_GATED, 0x9c20924e, abi.encodeWithSelector(
                0x9c20924e, bytes32(0), bytes32(0), address(0), false
            )
        );
        pairs[34] = SweepPair(2, KIND_GATED, 0xaa8ec927, abi.encodeWithSelector(0xaa8ec927, bytes32(0)));
        pairs[35] = SweepPair(2, KIND_GATED, 0xb99c738f, abi.encodeWithSelector(0xb99c738f, bytes32(0), uint256(0)));
        pairs[36] = SweepPair(
            2, KIND_SEAM, 0xc0c53b8b, abi.encodeWithSelector(
                0xc0c53b8b, address(0), address(0), address(0)
            )
        );
        pairs[37] = SweepPair(2, KIND_GATED, 0xcf1c9e6d, abi.encodeWithSelector(0xcf1c9e6d));
        pairs[38] = SweepPair(2, KIND_GATED, 0xece57ffb, abi.encodeWithSelector(0xece57ffb));
        pairs[39] = SweepPair(2, KIND_GATED, 0xf2fde38b, abi.encodeWithSelector(0xf2fde38b, address(0)));
        pairs[40] = SweepPair(3, KIND_GATED, 0x33f3d628, abi.encodeWithSelector(0x33f3d628, address(0), uint256(0)));
        pairs[41] = SweepPair(3, KIND_GATED, 0x37f8b2b8, abi.encodeWithSelector(0x37f8b2b8, address(0)));
        pairs[42] = SweepPair(3, KIND_GATED, 0x40b62a65, abi.encodeWithSelector(0x40b62a65, address(0)));
        pairs[43] = SweepPair(3, KIND_SEAM, 0x58bf3c7f, abi.encodeWithSelector(0x58bf3c7f, address(0)));
        pairs[44] = SweepPair(3, KIND_GATED, 0x86d1a69f, abi.encodeWithSelector(0x86d1a69f));
        pairs[45] = SweepPair(3, KIND_GATED, 0xa38547bb, abi.encodeWithSelector(0xa38547bb, address(0)));
        pairs[46] = SweepPair(3, KIND_GATED, 0xaef18ae7, abi.encodeWithSelector(0xaef18ae7, address(0)));
        pairs[47] = SweepPair(3, KIND_GATED, 0xd6a11777, abi.encodeWithSelector(0xd6a11777, address(0)));
        pairs[48] = SweepPair(3, KIND_GATED, 0xf3ff955a, abi.encodeWithSelector(0xf3ff955a, address(0)));
        pairs[49] = SweepPair(4, KIND_GATED, 0x3ae7fd8a, abi.encodeWithSelector(0x3ae7fd8a, uint256(0)));
        pairs[50] = SweepPair(
            4, KIND_GATED, 0x42bc0b4d, abi.encodeWithSelector(
                0x42bc0b4d, uint256(0), address(0), uint256(0), new bytes32[](0)
            )
        );
        pairs[51] = SweepPair(4, KIND_SEAM, 0x485cc955, abi.encodeWithSelector(0x485cc955, address(0), address(0)));
        pairs[52] = SweepPair(4, KIND_GATED, 0x4f1ef286, abi.encodeWithSelector(0x4f1ef286, address(0), ""));
        pairs[53] = SweepPair(4, KIND_SEAM, 0x58bf3c7f, abi.encodeWithSelector(0x58bf3c7f, address(0)));
        pairs[54] = SweepPair(4, KIND_GATED, 0x64bcc62c, abi.encodeWithSelector(0x64bcc62c, uint256(0), address(0)));
        pairs[55] = SweepPair(4, KIND_GATED, 0x75619ab5, abi.encodeWithSelector(0x75619ab5, address(0)));
        pairs[56] = SweepPair(4, KIND_GATED, 0x79ba5097, abi.encodeWithSelector(0x79ba5097));
        pairs[57] = SweepPair(4, KIND_GATED, 0x9108b293, abi.encodeWithSelector(0x9108b293));
        pairs[58] = SweepPair(
            4, KIND_GATED, 0x97386875, abi.encodeWithSelector(
                0x97386875, uint256(0), address(0), uint256(0), new bytes32[](0)
            )
        );
        pairs[59] = SweepPair(
            4, KIND_GATED, 0x9a37824d, abi.encodeWithSelector(
                0x9a37824d, uint256(0), bytes32(0), uint256(0), uint64(0)
            )
        );
        pairs[60] = SweepPair(4, KIND_GATED, 0xaef18ae7, abi.encodeWithSelector(0xaef18ae7, address(0)));
        pairs[61] = SweepPair(
            4, KIND_GATED, 0xb00005a4, abi.encodeWithSelector(
                0xb00005a4, uint256(0), bytes32(0), uint256(0), uint64(0)
            )
        );
        pairs[62] = SweepPair(
            4, KIND_GATED, 0xd5b27e76, abi.encodeWithSelector(
                0xd5b27e76, address(0), address(0), uint256(0), uint64(0), uint64(0), uint64(0)
            )
        );
        pairs[63] = SweepPair(
            4, KIND_GATED, 0xdbf9e393, abi.encodeWithSelector(
                0xdbf9e393, uint256(0), address(0), uint256(0), new bytes32[](0)
            )
        );
        pairs[64] = SweepPair(4, KIND_GATED, 0xf2fde38b, abi.encodeWithSelector(0xf2fde38b, address(0)));
        pairs[65] = SweepPair(4, KIND_GATED, 0xf7828e3e, abi.encodeWithSelector(0xf7828e3e, uint256(0), address(0)));
        pairs[66] = SweepPair(
            5, KIND_GATED, 0x150b7a02, abi.encodeWithSelector(
                0x150b7a02, address(0), address(0), uint256(0), ""
            )
        );
        pairs[67] = SweepPair(
            5, KIND_GATED, 0x160cbed7, abi.encodeWithSelector(
                0x160cbed7, new address[](0), new uint256[](0), new bytes[](0), bytes32(0)
            )
        );
        pairs[68] = SweepPair(
            5, KIND_GATED, 0x2656227d, abi.encodeWithSelector(
                0x2656227d, new address[](0), new uint256[](0), new bytes[](0), bytes32(0)
            )
        );
        pairs[69] = SweepPair(
            5, KIND_GATED, 0x452115d6, abi.encodeWithSelector(
                0x452115d6, new address[](0), new uint256[](0), new bytes[](0), bytes32(0)
            )
        );
        pairs[70] = SweepPair(5, KIND_GATED, 0x4f1ef286, abi.encodeWithSelector(0x4f1ef286, address(0), ""));
        pairs[71] = SweepPair(5, KIND_GATED, 0x56781388, abi.encodeWithSelector(0x56781388, uint256(0), uint8(0)));
        pairs[72] = SweepPair(5, KIND_SEAM, 0x58bf3c7f, abi.encodeWithSelector(0x58bf3c7f, address(0)));
        pairs[73] = SweepPair(
            5, KIND_GATED, 0x5b8d0e0d, abi.encodeWithSelector(
                0x5b8d0e0d, uint256(0), uint8(0), address(0), "", "", ""
            )
        );
        pairs[74] = SweepPair(
            5, KIND_SEAM, 0x5ec95384, abi.encodeWithSelector(
                0x5ec95384, address(0), address(0), uint48(0), uint32(0), uint256(0), uint256(0), address(0)
            )
        );
        pairs[75] = SweepPair(
            5, KIND_GATED, 0x5f398a14, abi.encodeWithSelector(
                0x5f398a14, uint256(0), uint8(0), "", ""
            )
        );
        pairs[76] = SweepPair(5, KIND_GATED, 0x6391c4e9, abi.encodeWithSelector(0x6391c4e9, uint256(0)));
        pairs[77] = SweepPair(5, KIND_GATED, 0x79051887, abi.encodeWithSelector(0x79051887, uint48(0)));
        pairs[78] = SweepPair(5, KIND_GATED, 0x7b3c71d3, abi.encodeWithSelector(0x7b3c71d3, uint256(0), uint8(0), ""));
        pairs[79] = SweepPair(
            5, KIND_GATED, 0x7d5e81e2, abi.encodeWithSelector(
                0x7d5e81e2, new address[](0), new uint256[](0), new bytes[](0), ""
            )
        );
        pairs[80] = SweepPair(
            5, KIND_GATED, 0x8ff262e3, abi.encodeWithSelector(
                0x8ff262e3, uint256(0), uint8(0), address(0), ""
            )
        );
        pairs[81] = SweepPair(5, KIND_GATED, 0xa815ca52, abi.encodeWithSelector(0xa815ca52, uint256(0)));
        pairs[82] = SweepPair(5, KIND_GATED, 0xa890c910, abi.encodeWithSelector(0xa890c910, address(0)));
        pairs[83] = SweepPair(
            5, KIND_GATED, 0xbc197c81, abi.encodeWithSelector(
                0xbc197c81, address(0), address(0), new uint256[](0), new uint256[](0), ""
            )
        );
        pairs[84] = SweepPair(
            5, KIND_GATED, 0xc28bc2fa, abi.encodeWithSelector(
                0xc28bc2fa, address(0), uint256(0), ""
            )
        );
        pairs[85] = SweepPair(5, KIND_GATED, 0xc62dfb3e, abi.encodeWithSelector(0xc62dfb3e));
        pairs[86] = SweepPair(5, KIND_GATED, 0xcf30013b, abi.encodeWithSelector(0xcf30013b, address(0)));
        pairs[87] = SweepPair(5, KIND_GATED, 0xe540d01d, abi.encodeWithSelector(0xe540d01d, uint32(0)));
        pairs[88] = SweepPair(5, KIND_GATED, 0xece40cc1, abi.encodeWithSelector(0xece40cc1, uint256(0)));
        pairs[89] = SweepPair(
            5, KIND_GATED, 0xf23a6e61, abi.encodeWithSelector(
                0xf23a6e61, address(0), address(0), uint256(0), uint256(0), ""
            )
        );
        pairs[90] = SweepPair(5, KIND_GATED, 0xfa99ba87, abi.encodeWithSelector(0xfa99ba87, uint256(0)));
        pairs[91] = SweepPair(6, KIND_EXEMPT, 0x095ea7b3, abi.encodeWithSelector(0x095ea7b3, address(0), uint256(0)));
        pairs[92] = SweepPair(6, KIND_GATED, 0x0ac28ff8, abi.encodeWithSelector(0x0ac28ff8, address(0), false));
        pairs[93] = SweepPair(6, KIND_GATED, 0x0c7ca007, abi.encodeWithSelector(0x0c7ca007, address(0), false));
        pairs[94] = SweepPair(
            6, KIND_GATED, 0x10233b43, abi.encodeWithSelector(
                0x10233b43, new address[](0), new uint256[](0)
            )
        );
        pairs[95] = SweepPair(
            6, KIND_EXEMPT, 0x23b872dd, abi.encodeWithSelector(
                0x23b872dd, address(0), address(0), uint256(0)
            )
        );
        pairs[96] = SweepPair(6, KIND_GATED, 0x26aefb5b, abi.encodeWithSelector(0x26aefb5b, address(0), false));
        pairs[97] = SweepPair(6, KIND_GATED, 0x282d3fdf, abi.encodeWithSelector(0x282d3fdf, address(0), uint256(0)));
        pairs[98] = SweepPair(6, KIND_GATED, 0x28b60487, abi.encodeWithSelector(0x28b60487, new address[](0)));
        pairs[99] = SweepPair(6, KIND_GATED, 0x4f1ef286, abi.encodeWithSelector(0x4f1ef286, address(0), ""));
        pairs[100] = SweepPair(6, KIND_SEAM, 0x58bf3c7f, abi.encodeWithSelector(0x58bf3c7f, address(0)));
        pairs[101] = SweepPair(6, KIND_GATED, 0x5c19a95c, abi.encodeWithSelector(0x5c19a95c, address(0)));
        pairs[102] = SweepPair(6, KIND_GATED, 0x79ba5097, abi.encodeWithSelector(0x79ba5097));
        pairs[103] = SweepPair(6, KIND_GATED, 0x7eee288d, abi.encodeWithSelector(0x7eee288d, address(0), uint256(0)));
        pairs[104] = SweepPair(6, KIND_GATED, 0x99aa477e, abi.encodeWithSelector(0x99aa477e, address(0), address(0)));
        pairs[105] = SweepPair(6, KIND_GATED, 0x9dc29fac, abi.encodeWithSelector(0x9dc29fac, address(0), uint256(0)));
        pairs[106] = SweepPair(6, KIND_EXEMPT, 0xa9059cbb, abi.encodeWithSelector(0xa9059cbb, address(0), uint256(0)));
        pairs[107] = SweepPair(6, KIND_GATED, 0xaef18ae7, abi.encodeWithSelector(0xaef18ae7, address(0)));
        pairs[108] = SweepPair(
            6, KIND_SEAM, 0xc0c53b8b, abi.encodeWithSelector(
                0xc0c53b8b, address(0), address(0), address(0)
            )
        );
        pairs[109] = SweepPair(6, KIND_GATED, 0xf2fde38b, abi.encodeWithSelector(0xf2fde38b, address(0)));
        pairs[110] = SweepPair(6, KIND_GATED, 0xf40d71f1, abi.encodeWithSelector(0xf40d71f1, address(0), uint256(0)));
        pairs[111] = SweepPair(
            7, KIND_GATED, 0x0dde60e8, abi.encodeWithSelector(
                0x0dde60e8, bytes32(0), address(0), address(0)
            )
        );
        pairs[112] = SweepPair(7, KIND_GATED, 0x2e2ec984, abi.encodeWithSelector(0x2e2ec984, address(0)));
        pairs[113] = SweepPair(
            7, KIND_GATED, 0x458d844d, abi.encodeWithSelector(
                0x458d844d, new address[](0), new uint256[](0), new bytes[](0)
            )
        );
        pairs[114] = SweepPair(7, KIND_GATED, 0x473ae8e7, abi.encodeWithSelector(0x473ae8e7, address(0)));
        pairs[115] = SweepPair(7, KIND_GATED, 0x4793539a, abi.encodeWithSelector(0x4793539a, address(0), uint256(0)));
        pairs[116] = SweepPair(7, KIND_GATED, 0x4f1ef286, abi.encodeWithSelector(0x4f1ef286, address(0), ""));
        pairs[117] = SweepPair(
            7, KIND_GATED, 0x56839375, abi.encodeWithSelector(
                0x56839375, bytes32(0), address(0), address(0)
            )
        );
        pairs[118] = SweepPair(7, KIND_SEAM, 0x58bf3c7f, abi.encodeWithSelector(0x58bf3c7f, address(0)));
        pairs[119] = SweepPair(7, KIND_GATED, 0x611de201, abi.encodeWithSelector(0x611de201, bytes32(0)));
        pairs[120] = SweepPair(7, KIND_GATED, 0x62f384ad, abi.encodeWithSelector(0x62f384ad, address(0)));
        pairs[121] = SweepPair(7, KIND_GATED, 0x71404156, abi.encodeWithSelector(0x71404156, address(0)));
        pairs[122] = SweepPair(7, KIND_GATED, 0x8a2c7b39, abi.encodeWithSelector(0x8a2c7b39));
        pairs[123] = SweepPair(7, KIND_GATED, 0xa6e897db, abi.encodeWithSelector(0xa6e897db, address(0), false));
        pairs[124] = SweepPair(
            7, KIND_GATED, 0xb02f3b99, abi.encodeWithSelector(
                0xb02f3b99, bytes32(0), address(0), address(0)
            )
        );
        pairs[125] = SweepPair(7, KIND_GATED, 0xbe1894cc, abi.encodeWithSelector(0xbe1894cc, bytes32(0)));
        pairs[126] = SweepPair(7, KIND_GATED, 0xdacf4452, abi.encodeWithSelector(0xdacf4452, uint256(0)));
        pairs[127] = SweepPair(
            7, KIND_SEAM, 0xed3c6694, abi.encodeWithSelector(
                0xed3c6694, address(0), address(0), new address[](0), new uint256[](0)
            )
        );
        pairs[128] = SweepPair(7, KIND_GATED, 0xfaba74dc, abi.encodeWithSelector(0xfaba74dc, bytes32(0)));
        pairs[129] = SweepPair(8, KIND_GATED, 0x028bfa48, abi.encodeWithSelector(0x028bfa48));
        pairs[130] = SweepPair(8, KIND_GATED, 0x14cda248, abi.encodeWithSelector(0x14cda248, uint256(0), false));
        pairs[131] = SweepPair(8, KIND_GATED, 0x1a354289, abi.encodeWithSelector(0x1a354289, uint256(0), false));
        pairs[132] = SweepPair(8, KIND_GATED, 0x1b3c7386, abi.encodeWithSelector(0x1b3c7386, uint256(0), uint256(0)));
        pairs[133] = SweepPair(8, KIND_GATED, 0x230fd519, abi.encodeWithSelector(0x230fd519));
        pairs[134] = SweepPair(8, KIND_GATED, 0x2412c6b4, abi.encodeWithSelector(0x2412c6b4, uint256(0)));
        pairs[135] = SweepPair(
            8, KIND_GATED, 0x26608f2a, abi.encodeWithSelector(
                0x26608f2a, uint256(0), uint256(0), uint256(0), uint256(0)
            )
        );
        pairs[136] = SweepPair(8, KIND_GATED, 0x2e899c14, abi.encodeWithSelector(0x2e899c14, uint256(0)));
        pairs[137] = SweepPair(8, KIND_GATED, 0x39b0839a, abi.encodeWithSelector(0x39b0839a, uint256(0)));
        pairs[138] = SweepPair(8, KIND_GATED, 0x3f4ba83a, abi.encodeWithSelector(0x3f4ba83a));
        pairs[139] = SweepPair(8, KIND_GATED, 0x4568b940, abi.encodeWithSelector(0x4568b940, false));
        pairs[140] = SweepPair(8, KIND_GATED, 0x4f1ef286, abi.encodeWithSelector(0x4f1ef286, address(0), ""));
        pairs[141] = SweepPair(8, KIND_SEAM, 0x58bf3c7f, abi.encodeWithSelector(0x58bf3c7f, address(0)));
        pairs[142] = SweepPair(8, KIND_GATED, 0x5b0ddf41, abi.encodeWithSelector(0x5b0ddf41, bytes32(0)));
        pairs[143] = SweepPair(8, KIND_GATED, 0x5f384b8f, abi.encodeWithSelector(0x5f384b8f, address(0)));
        pairs[144] = SweepPair(8, KIND_GATED, 0x705d2c25, abi.encodeWithSelector(0x705d2c25, uint256(0)));
        pairs[145] = SweepPair(8, KIND_GATED, 0x77257be4, abi.encodeWithSelector(0x77257be4, uint256(0)));
        pairs[146] = SweepPair(8, KIND_GATED, 0x79ba5097, abi.encodeWithSelector(0x79ba5097));
        pairs[147] = SweepPair(
            8, KIND_GATED, 0x7d58d438, abi.encodeWithSelector(
                0x7d58d438, uint256(0), address(0), bytes32(0), uint64(0)
            )
        );
        pairs[148] = SweepPair(8, KIND_GATED, 0x8456cb59, abi.encodeWithSelector(0x8456cb59));
        pairs[149] = SweepPair(8, KIND_GATED, 0x91f6efe8, abi.encodeWithSelector(0x91f6efe8, address(0)));
        pairs[150] = SweepPair(8, KIND_GATED, 0x9c3550d2, abi.encodeWithSelector(0x9c3550d2, bytes32(0), uint256(0)));
        pairs[151] = SweepPair(8, KIND_GATED, 0xaef18ae7, abi.encodeWithSelector(0xaef18ae7, address(0)));
        pairs[152] = SweepPair(
            8, KIND_SEAM, 0xb08c220c, abi.encodeWithSelector(
                0xb08c220c, address(0), address(0), address(0), address(0), address(0), address(0), address(0), address(0), HLTradingBridge.RouteConfig(address(0), bytes32(0), uint64(0), address(0))
            )
        );
        pairs[153] = SweepPair(8, KIND_GATED, 0xb7d91257, abi.encodeWithSelector(0xb7d91257));
        pairs[154] = SweepPair(8, KIND_GATED, 0xb8f44963, abi.encodeWithSelector(0xb8f44963, address(0)));
        pairs[155] = SweepPair(8, KIND_GATED, 0xb9cf4892, abi.encodeWithSelector(0xb9cf4892, uint256(0), uint256(0)));
        pairs[156] = SweepPair(8, KIND_GATED, 0xc49aef59, abi.encodeWithSelector(0xc49aef59, uint16(0), uint16(0)));
        pairs[157] = SweepPair(8, KIND_GATED, 0xce81612d, abi.encodeWithSelector(0xce81612d, uint16(0), uint16(0)));
        pairs[158] = SweepPair(8, KIND_GATED, 0xd19030fc, abi.encodeWithSelector(0xd19030fc, uint256(0)));
        pairs[159] = SweepPair(
            8, KIND_GATED, 0xdc6d3e3b, abi.encodeWithSelector(
                0xdc6d3e3b, uint256(0), address(0), bytes32(0), uint64(0)
            )
        );
        pairs[160] = SweepPair(8, KIND_GATED, 0xf2fde38b, abi.encodeWithSelector(0xf2fde38b, address(0)));
        pairs[161] = SweepPair(9, KIND_EXEMPT, 0x095ea7b3, abi.encodeWithSelector(0x095ea7b3, address(0), uint256(0)));
        pairs[162] = SweepPair(9, KIND_GATED, 0x165709d7, abi.encodeWithSelector(0x165709d7, address(0)));
        pairs[163] = SweepPair(
            9, KIND_EXEMPT, 0x23b872dd, abi.encodeWithSelector(
                0x23b872dd, address(0), address(0), uint256(0)
            )
        );
        pairs[164] = SweepPair(9, KIND_GATED, 0x3f4ba83a, abi.encodeWithSelector(0x3f4ba83a));
        pairs[165] = SweepPair(9, KIND_GATED, 0x40c10f19, abi.encodeWithSelector(0x40c10f19, address(0), uint256(0)));
        pairs[166] = SweepPair(9, KIND_GATED, 0x4f1ef286, abi.encodeWithSelector(0x4f1ef286, address(0), ""));
        pairs[167] = SweepPair(9, KIND_GATED, 0x50d2fcc4, abi.encodeWithSelector(0x50d2fcc4, address(0)));
        pairs[168] = SweepPair(9, KIND_SEAM, 0x58bf3c7f, abi.encodeWithSelector(0x58bf3c7f, address(0)));
        pairs[169] = SweepPair(9, KIND_GATED, 0x6c714774, abi.encodeWithSelector(0x6c714774));
        pairs[170] = SweepPair(9, KIND_GATED, 0x79ba5097, abi.encodeWithSelector(0x79ba5097));
        pairs[171] = SweepPair(9, KIND_GATED, 0x8456cb59, abi.encodeWithSelector(0x8456cb59));
        pairs[172] = SweepPair(9, KIND_GATED, 0x884227d6, abi.encodeWithSelector(0x884227d6, address(0), false));
        pairs[173] = SweepPair(9, KIND_GATED, 0x9dc29fac, abi.encodeWithSelector(0x9dc29fac, address(0), uint256(0)));
        pairs[174] = SweepPair(9, KIND_EXEMPT, 0xa9059cbb, abi.encodeWithSelector(0xa9059cbb, address(0), uint256(0)));
        pairs[175] = SweepPair(9, KIND_GATED, 0xaef18ae7, abi.encodeWithSelector(0xaef18ae7, address(0)));
        pairs[176] = SweepPair(9, KIND_GATED, 0xb309d6b7, abi.encodeWithSelector(0xb309d6b7));
        pairs[177] = SweepPair(9, KIND_SEAM, 0xc4d66de8, abi.encodeWithSelector(0xc4d66de8, address(0)));
        pairs[178] = SweepPair(9, KIND_GATED, 0xcbd956c3, abi.encodeWithSelector(0xcbd956c3));
        pairs[179] = SweepPair(9, KIND_GATED, 0xdd3f5aac, abi.encodeWithSelector(0xdd3f5aac));
        pairs[180] = SweepPair(9, KIND_GATED, 0xece57ffb, abi.encodeWithSelector(0xece57ffb));
        pairs[181] = SweepPair(9, KIND_GATED, 0xf2fde38b, abi.encodeWithSelector(0xf2fde38b, address(0)));
        pairs[182] = SweepPair(9, KIND_GATED, 0xfca3b5aa, abi.encodeWithSelector(0xfca3b5aa, address(0)));
        pairs[183] = SweepPair(10, KIND_GATED, 0x00781185, abi.encodeWithSelector(0x00781185, uint256(0)));
        pairs[184] = SweepPair(10, KIND_GATED, 0x076a760c, abi.encodeWithSelector(0x076a760c));
        pairs[185] = SweepPair(10, KIND_GATED, 0x0930b617, abi.encodeWithSelector(0x0930b617, uint256(0)));
        pairs[186] = SweepPair(10, KIND_GATED, 0x120db14c, abi.encodeWithSelector(0x120db14c, uint256(0)));
        pairs[187] = SweepPair(10, KIND_GATED, 0x12c20f9f, abi.encodeWithSelector(0x12c20f9f, address(0)));
        pairs[188] = SweepPair(10, KIND_GATED, 0x12c55e92, abi.encodeWithSelector(0x12c55e92, uint256(0)));
        pairs[189] = SweepPair(10, KIND_GATED, 0x15f20c10, abi.encodeWithSelector(0x15f20c10, address(0)));
        pairs[190] = SweepPair(10, KIND_GATED, 0x1611d407, abi.encodeWithSelector(0x1611d407, uint256(0)));
        pairs[191] = SweepPair(10, KIND_GATED, 0x165709d7, abi.encodeWithSelector(0x165709d7, address(0)));
        pairs[192] = SweepPair(10, KIND_GATED, 0x18ace25f, abi.encodeWithSelector(0x18ace25f, uint256(0), uint256(0)));
        pairs[193] = SweepPair(
            10, KIND_SEAM, 0x1b8861d5, abi.encodeWithSelector(
                0x1b8861d5, address(0), address(0), address(0), address(0), address(0)
            )
        );
        pairs[194] = SweepPair(10, KIND_GATED, 0x1e31832b, abi.encodeWithSelector(0x1e31832b, uint256(0), uint256(0)));
        pairs[195] = SweepPair(
            10, KIND_GATED, 0x1fa3c376, abi.encodeWithSelector(
                0x1fa3c376, address(0), uint256(0), address(0)
            )
        );
        pairs[196] = SweepPair(10, KIND_GATED, 0x21972115, abi.encodeWithSelector(0x21972115, address(0)));
        pairs[197] = SweepPair(10, KIND_GATED, 0x29b6eca9, abi.encodeWithSelector(0x29b6eca9, address(0)));
        pairs[198] = SweepPair(10, KIND_GATED, 0x2b290ec0, abi.encodeWithSelector(0x2b290ec0));
        pairs[199] = SweepPair(10, KIND_GATED, 0x3182d0a7, abi.encodeWithSelector(0x3182d0a7, uint256(0)));
        pairs[200] = SweepPair(10, KIND_GATED, 0x3aa43556, abi.encodeWithSelector(0x3aa43556, uint256(0), uint256(0)));
        pairs[201] = SweepPair(10, KIND_GATED, 0x3f4ba83a, abi.encodeWithSelector(0x3f4ba83a));
        pairs[202] = SweepPair(10, KIND_GATED, 0x403f3731, abi.encodeWithSelector(0x403f3731, address(0)));
        pairs[203] = SweepPair(10, KIND_GATED, 0x412b6ffc, abi.encodeWithSelector(0x412b6ffc, address(0)));
        pairs[204] = SweepPair(10, KIND_GATED, 0x448bb745, abi.encodeWithSelector(0x448bb745, uint256(0)));
        pairs[205] = SweepPair(10, KIND_GATED, 0x477cf757, abi.encodeWithSelector(0x477cf757, address(0)));
        pairs[206] = SweepPair(10, KIND_GATED, 0x4f1ef286, abi.encodeWithSelector(0x4f1ef286, address(0), ""));
        pairs[207] = SweepPair(10, KIND_GATED, 0x552670c4, abi.encodeWithSelector(0x552670c4));
        pairs[208] = SweepPair(10, KIND_SEAM, 0x58bf3c7f, abi.encodeWithSelector(0x58bf3c7f, address(0)));
        pairs[209] = SweepPair(10, KIND_GATED, 0x6992b420, abi.encodeWithSelector(0x6992b420, uint8(0), uint256(0)));
        pairs[210] = SweepPair(10, KIND_GATED, 0x6d064af2, abi.encodeWithSelector(0x6d064af2, uint256(0), false));
        pairs[211] = SweepPair(10, KIND_GATED, 0x771084fa, abi.encodeWithSelector(0x771084fa));
        pairs[212] = SweepPair(10, KIND_GATED, 0x786f1a6a, abi.encodeWithSelector(0x786f1a6a, false));
        pairs[213] = SweepPair(10, KIND_GATED, 0x79ba5097, abi.encodeWithSelector(0x79ba5097));
        pairs[214] = SweepPair(10, KIND_SEAM, 0x81ada323, abi.encodeWithSelector(0x81ada323, address(0)));
        pairs[215] = SweepPair(10, KIND_GATED, 0x826309a3, abi.encodeWithSelector(0x826309a3));
        pairs[216] = SweepPair(10, KIND_GATED, 0x8456cb59, abi.encodeWithSelector(0x8456cb59));
        pairs[217] = SweepPair(10, KIND_GATED, 0x8554ba15, abi.encodeWithSelector(0x8554ba15, uint256(0)));
        pairs[218] = SweepPair(10, KIND_GATED, 0x8de7c38b, abi.encodeWithSelector(0x8de7c38b, uint256(0)));
        pairs[219] = SweepPair(10, KIND_GATED, 0x8e8fdf6c, abi.encodeWithSelector(0x8e8fdf6c, uint256(0)));
        pairs[220] = SweepPair(
            10, KIND_GATED, 0x910bd7e5, abi.encodeWithSelector(
                0x910bd7e5, uint256(0), uint256(0), uint256(0), uint256(0)
            )
        );
        pairs[221] = SweepPair(
            10, KIND_GATED, 0xa4e31bed, abi.encodeWithSelector(
                0xa4e31bed, uint256(0), uint256(0), uint256(0)
            )
        );
        pairs[222] = SweepPair(10, KIND_GATED, 0xa5c71b0c, abi.encodeWithSelector(0xa5c71b0c, uint256(0)));
        pairs[223] = SweepPair(
            10, KIND_GATED, 0xa88f6809, abi.encodeWithSelector(
                0xa88f6809, uint256(0), uint256(0), uint256(0)
            )
        );
        pairs[224] = SweepPair(
            10, KIND_GATED, 0xa9fcf148, abi.encodeWithSelector(
                0xa9fcf148, uint256(0), uint256(0), uint256(0)
            )
        );
        pairs[225] = SweepPair(10, KIND_GATED, 0xae2b4248, abi.encodeWithSelector(0xae2b4248));
        pairs[226] = SweepPair(10, KIND_GATED, 0xaef18ae7, abi.encodeWithSelector(0xaef18ae7, address(0)));
        pairs[227] = SweepPair(10, KIND_GATED, 0xb309d6b7, abi.encodeWithSelector(0xb309d6b7));
        pairs[228] = SweepPair(10, KIND_GATED, 0xb6b55f25, abi.encodeWithSelector(0xb6b55f25, uint256(0)));
        pairs[229] = SweepPair(10, KIND_GATED, 0xbbe3971f, abi.encodeWithSelector(0xbbe3971f));
        pairs[230] = SweepPair(10, KIND_GATED, 0xc055bfeb, abi.encodeWithSelector(0xc055bfeb));
        pairs[231] = SweepPair(
            10, KIND_SEAM, 0xc0c53b8b, abi.encodeWithSelector(
                0xc0c53b8b, address(0), address(0), address(0)
            )
        );
        pairs[232] = SweepPair(10, KIND_GATED, 0xca079a38, abi.encodeWithSelector(0xca079a38, uint256(0)));
        pairs[233] = SweepPair(10, KIND_GATED, 0xd2008d27, abi.encodeWithSelector(0xd2008d27));
        pairs[234] = SweepPair(10, KIND_GATED, 0xda91fa5c, abi.encodeWithSelector(0xda91fa5c, uint256(0)));
        pairs[235] = SweepPair(10, KIND_GATED, 0xdb006a75, abi.encodeWithSelector(0xdb006a75, uint256(0)));
        pairs[236] = SweepPair(10, KIND_GATED, 0xdfcd8fb5, abi.encodeWithSelector(0xdfcd8fb5));
        pairs[237] = SweepPair(10, KIND_GATED, 0xe1ed3f33, abi.encodeWithSelector(0xe1ed3f33));
        pairs[238] = SweepPair(10, KIND_GATED, 0xe6e6bbbc, abi.encodeWithSelector(0xe6e6bbbc, uint256(0)));
        pairs[239] = SweepPair(
            10, KIND_GATED, 0xe79b9c1f, abi.encodeWithSelector(
                0xe79b9c1f, uint256(0), uint256(0), uint256(0)
            )
        );
        pairs[240] = SweepPair(10, KIND_GATED, 0xece57ffb, abi.encodeWithSelector(0xece57ffb));
        pairs[241] = SweepPair(10, KIND_GATED, 0xf2fde38b, abi.encodeWithSelector(0xf2fde38b, address(0)));
        pairs[242] = SweepPair(10, KIND_GATED, 0xf467bc66, abi.encodeWithSelector(0xf467bc66, address(0)));
        pairs[243] = SweepPair(10, KIND_GATED, 0xf57e9254, abi.encodeWithSelector(0xf57e9254, uint256(0)));
        pairs[244] = SweepPair(10, KIND_GATED, 0xf9252d2f, abi.encodeWithSelector(0xf9252d2f));
        pairs[245] = SweepPair(10, KIND_GATED, 0xfee5e6e8, abi.encodeWithSelector(0xfee5e6e8, uint256(0)));
        pairs[246] = SweepPair(10, KIND_GATED, 0xfff907f1, abi.encodeWithSelector(0xfff907f1, uint256(0)));
        pairs[247] = SweepPair(11, KIND_GATED, 0x07cf3ffa, abi.encodeWithSelector(0x07cf3ffa));
        pairs[248] = SweepPair(11, KIND_GATED, 0x121e992f, abi.encodeWithSelector(0x121e992f, address(0), uint256(0)));
        pairs[249] = SweepPair(11, KIND_GATED, 0x165709d7, abi.encodeWithSelector(0x165709d7, address(0)));
        pairs[250] = SweepPair(
            11, KIND_GATED, 0x1bf18043, abi.encodeWithSelector(
                0x1bf18043, uint256(0), uint256(0), uint256(0)
            )
        );
        pairs[251] = SweepPair(11, KIND_GATED, 0x1c39bac4, abi.encodeWithSelector(0x1c39bac4));
        pairs[252] = SweepPair(
            11, KIND_GATED, 0x1fae3723, abi.encodeWithSelector(
                0x1fae3723, uint256(0), uint8(0), uint256(0), uint256(0)
            )
        );
        pairs[253] = SweepPair(11, KIND_GATED, 0x210cf816, abi.encodeWithSelector(0x210cf816, uint256(0)));
        pairs[254] = SweepPair(
            11, KIND_GATED, 0x2155ba09, abi.encodeWithSelector(
                0x2155ba09, address(0), uint8(0), address(0), address(0)
            )
        );
        pairs[255] = SweepPair(11, KIND_GATED, 0x290da231, abi.encodeWithSelector(0x290da231));
        pairs[256] = SweepPair(
            11, KIND_GATED, 0x298a8a30, abi.encodeWithSelector(
                0x298a8a30, StakingQueue.PriceMode(0)
            )
        );
        pairs[257] = SweepPair(11, KIND_GATED, 0x3b1476a2, abi.encodeWithSelector(0x3b1476a2, address(0), uint256(0)));
        pairs[258] = SweepPair(11, KIND_GATED, 0x3c128b6c, abi.encodeWithSelector(0x3c128b6c, uint8(0), uint256(0)));
        pairs[259] = SweepPair(
            11, KIND_GATED, 0x3ebade71, abi.encodeWithSelector(
                0x3ebade71, StakingQueue.PriceMode(0)
            )
        );
        pairs[260] = SweepPair(11, KIND_GATED, 0x3f4ba83a, abi.encodeWithSelector(0x3f4ba83a));
        pairs[261] = SweepPair(11, KIND_GATED, 0x443b04d0, abi.encodeWithSelector(0x443b04d0, uint8(0), uint256(0)));
        pairs[262] = SweepPair(11, KIND_GATED, 0x4e2c8842, abi.encodeWithSelector(0x4e2c8842, uint8(0), false));
        pairs[263] = SweepPair(11, KIND_GATED, 0x4f1ef286, abi.encodeWithSelector(0x4f1ef286, address(0), ""));
        pairs[264] = SweepPair(11, KIND_SEAM, 0x58bf3c7f, abi.encodeWithSelector(0x58bf3c7f, address(0)));
        pairs[265] = SweepPair(11, KIND_GATED, 0x5b8f6839, abi.encodeWithSelector(0x5b8f6839));
        pairs[266] = SweepPair(11, KIND_GATED, 0x6c084c65, abi.encodeWithSelector(0x6c084c65, uint256(0), uint8(0)));
        pairs[267] = SweepPair(11, KIND_GATED, 0x6d77651c, abi.encodeWithSelector(0x6d77651c));
        pairs[268] = SweepPair(11, KIND_GATED, 0x715018a6, abi.encodeWithSelector(0x715018a6));
        pairs[269] = SweepPair(11, KIND_GATED, 0x79ba5097, abi.encodeWithSelector(0x79ba5097));
        pairs[270] = SweepPair(11, KIND_GATED, 0x7f79f488, abi.encodeWithSelector(0x7f79f488, address(0), false));
        pairs[271] = SweepPair(11, KIND_GATED, 0x82f8f0ea, abi.encodeWithSelector(0x82f8f0ea, uint256(0)));
        pairs[272] = SweepPair(
            11, KIND_GATED, 0x83f0f14c, abi.encodeWithSelector(
                0x83f0f14c, uint8(0), uint8(0), uint256(0)
            )
        );
        pairs[273] = SweepPair(11, KIND_GATED, 0x8456cb59, abi.encodeWithSelector(0x8456cb59));
        pairs[274] = SweepPair(11, KIND_GATED, 0x8522030a, abi.encodeWithSelector(0x8522030a, uint256(0)));
        pairs[275] = SweepPair(
            11, KIND_GATED, 0x8e86852f, abi.encodeWithSelector(
                0x8e86852f, uint256(0), uint256(0), uint256(0)
            )
        );
        pairs[276] = SweepPair(11, KIND_GATED, 0x8f496ee2, abi.encodeWithSelector(0x8f496ee2, uint8(0), uint256(0)));
        pairs[277] = SweepPair(
            11, KIND_SEAM, 0x91b5cf77, abi.encodeWithSelector(
                0x91b5cf77, address(0), address(0), [address(0), address(0), address(0), address(0)], address(0), address(0)
            )
        );
        pairs[278] = SweepPair(11, KIND_GATED, 0xa2f83a8a, abi.encodeWithSelector(0xa2f83a8a, uint256(0), address(0)));
        pairs[279] = SweepPair(11, KIND_GATED, 0xa684db3a, abi.encodeWithSelector(0xa684db3a, uint256(0)));
        pairs[280] = SweepPair(11, KIND_GATED, 0xaef18ae7, abi.encodeWithSelector(0xaef18ae7, address(0)));
        pairs[281] = SweepPair(
            11, KIND_GATED, 0xb0b8850f, abi.encodeWithSelector(
                0xb0b8850f, new address[](0), uint8(0)
            )
        );
        pairs[282] = SweepPair(11, KIND_GATED, 0xb18c312d, abi.encodeWithSelector(0xb18c312d, uint256(0)));
        pairs[283] = SweepPair(11, KIND_GATED, 0xb309d6b7, abi.encodeWithSelector(0xb309d6b7));
        pairs[284] = SweepPair(11, KIND_GATED, 0xb8f44963, abi.encodeWithSelector(0xb8f44963, address(0)));
        pairs[285] = SweepPair(11, KIND_GATED, 0xbac22bb8, abi.encodeWithSelector(0xbac22bb8));
        pairs[286] = SweepPair(11, KIND_GATED, 0xbd282d02, abi.encodeWithSelector(0xbd282d02));
        pairs[287] = SweepPair(11, KIND_GATED, 0xca0c4ec4, abi.encodeWithSelector(0xca0c4ec4));
        pairs[288] = SweepPair(11, KIND_GATED, 0xe668b870, abi.encodeWithSelector(0xe668b870, uint8(0)));
        pairs[289] = SweepPair(11, KIND_GATED, 0xece57ffb, abi.encodeWithSelector(0xece57ffb));
        pairs[290] = SweepPair(11, KIND_SEAM, 0xefb6ed47, abi.encodeWithSelector(0xefb6ed47, address(0)));
        pairs[291] = SweepPair(11, KIND_GATED, 0xf2c70aa3, abi.encodeWithSelector(0xf2c70aa3, uint256(0)));
        pairs[292] = SweepPair(11, KIND_GATED, 0xf2fde38b, abi.encodeWithSelector(0xf2fde38b, address(0)));
        pairs[293] = SweepPair(11, KIND_GATED, 0xffb6c6b6, abi.encodeWithSelector(0xffb6c6b6, uint256(0)));
        pairs[294] = SweepPair(12, KIND_GATED, 0x1b3c7386, abi.encodeWithSelector(0x1b3c7386, uint256(0), uint256(0)));
        pairs[295] = SweepPair(12, KIND_GATED, 0x337d4c4a, abi.encodeWithSelector(0x337d4c4a, uint256(0)));
        pairs[296] = SweepPair(12, KIND_GATED, 0x3aa43556, abi.encodeWithSelector(0x3aa43556, uint256(0), uint256(0)));
        pairs[297] = SweepPair(12, KIND_GATED, 0x4f1ef286, abi.encodeWithSelector(0x4f1ef286, address(0), ""));
        pairs[298] = SweepPair(12, KIND_GATED, 0x515b2fb0, abi.encodeWithSelector(0x515b2fb0, address(0)));
        pairs[299] = SweepPair(12, KIND_SEAM, 0x58bf3c7f, abi.encodeWithSelector(0x58bf3c7f, address(0)));
        pairs[300] = SweepPair(
            12, KIND_GATED, 0x6664ac91, abi.encodeWithSelector(
                0x6664ac91, bytes32(0), address(0), uint256(0)
            )
        );
        pairs[301] = SweepPair(12, KIND_GATED, 0x73d50309, abi.encodeWithSelector(0x73d50309));
        pairs[302] = SweepPair(12, KIND_GATED, 0x75619ab5, abi.encodeWithSelector(0x75619ab5, address(0)));
        pairs[303] = SweepPair(12, KIND_GATED, 0x756e12fd, abi.encodeWithSelector(0x756e12fd));
        pairs[304] = SweepPair(12, KIND_GATED, 0x79ba5097, abi.encodeWithSelector(0x79ba5097));
        pairs[305] = SweepPair(12, KIND_GATED, 0x8554ba15, abi.encodeWithSelector(0x8554ba15, uint256(0)));
        pairs[306] = SweepPair(
            12, KIND_SEAM, 0x8a29e2de, abi.encodeWithSelector(
                0x8a29e2de, address(0), address(0), address(0), address(0), address(0), address(0), address(0), address(0)
            )
        );
        pairs[307] = SweepPair(12, KIND_GATED, 0x9108b293, abi.encodeWithSelector(0x9108b293));
        pairs[308] = SweepPair(12, KIND_GATED, 0x93c1726b, abi.encodeWithSelector(0x93c1726b, address(0)));
        pairs[309] = SweepPair(12, KIND_GATED, 0xa63cd377, abi.encodeWithSelector(0xa63cd377, uint256(0), int256(0)));
        pairs[310] = SweepPair(12, KIND_GATED, 0xa7654a8c, abi.encodeWithSelector(0xa7654a8c, uint256(0)));
        pairs[311] = SweepPair(
            12, KIND_GATED, 0xa9fcf148, abi.encodeWithSelector(
                0xa9fcf148, uint256(0), uint256(0), uint256(0)
            )
        );
        pairs[312] = SweepPair(12, KIND_GATED, 0xaef18ae7, abi.encodeWithSelector(0xaef18ae7, address(0)));
        pairs[313] = SweepPair(12, KIND_GATED, 0xd12260d8, abi.encodeWithSelector(0xd12260d8, address(0)));
        pairs[314] = SweepPair(
            12, KIND_GATED, 0xd1f74f86, abi.encodeWithSelector(
                0xd1f74f86, new address[](0), new uint256[](0)
            )
        );
        pairs[315] = SweepPair(12, KIND_GATED, 0xf04416c3, abi.encodeWithSelector(0xf04416c3, uint256(0)));
        pairs[316] = SweepPair(12, KIND_GATED, 0xf2fde38b, abi.encodeWithSelector(0xf2fde38b, address(0)));
        pairs[317] = SweepPair(13, KIND_GATED, 0x0411e2f6, abi.encodeWithSelector(0x0411e2f6, uint256(0)));
        pairs[318] = SweepPair(13, KIND_GATED, 0x13186f0c, abi.encodeWithSelector(0x13186f0c, uint256(0)));
        pairs[319] = SweepPair(13, KIND_GATED, 0x1df9c0b0, abi.encodeWithSelector(0x1df9c0b0, uint256(0)));
        pairs[320] = SweepPair(13, KIND_GATED, 0x29b6eca9, abi.encodeWithSelector(0x29b6eca9, address(0)));
        pairs[321] = SweepPair(13, KIND_GATED, 0x38e454b1, abi.encodeWithSelector(0x38e454b1));
        pairs[322] = SweepPair(
            13, KIND_GATED, 0x4a968995, abi.encodeWithSelector(
                0x4a968995, uint256(0), [uint16(0), uint16(0), uint16(0), uint16(0)], [uint16(0), uint16(0), uint16(0), uint16(0)]
            )
        );
        pairs[323] = SweepPair(13, KIND_GATED, 0x4f1ef286, abi.encodeWithSelector(0x4f1ef286, address(0), ""));
        pairs[324] = SweepPair(13, KIND_GATED, 0x54a08606, abi.encodeWithSelector(0x54a08606));
        pairs[325] = SweepPair(13, KIND_SEAM, 0x58bf3c7f, abi.encodeWithSelector(0x58bf3c7f, address(0)));
        pairs[326] = SweepPair(
            13, KIND_GATED, 0x6a5172cf, abi.encodeWithSelector(
                0x6a5172cf, uint256(0), [uint16(0), uint16(0), uint16(0), uint16(0)], [uint16(0), uint16(0), uint16(0), uint16(0)]
            )
        );
        pairs[327] = SweepPair(13, KIND_GATED, 0x79ba5097, abi.encodeWithSelector(0x79ba5097));
        pairs[328] = SweepPair(13, KIND_GATED, 0x7fea40e4, abi.encodeWithSelector(0x7fea40e4));
        pairs[329] = SweepPair(13, KIND_GATED, 0x98f8b427, abi.encodeWithSelector(0x98f8b427, uint256(0), uint256(0)));
        pairs[330] = SweepPair(13, KIND_GATED, 0xa0feb6eb, abi.encodeWithSelector(0xa0feb6eb));
        pairs[331] = SweepPair(13, KIND_GATED, 0xbe883320, abi.encodeWithSelector(0xbe883320, uint256(0)));
        pairs[332] = SweepPair(13, KIND_GATED, 0xc150ad1a, abi.encodeWithSelector(0xc150ad1a, uint256(0)));
        pairs[333] = SweepPair(13, KIND_SEAM, 0xc4d66de8, abi.encodeWithSelector(0xc4d66de8, address(0)));
        pairs[334] = SweepPair(13, KIND_GATED, 0xcf54068d, abi.encodeWithSelector(0xcf54068d, uint256(0)));
        pairs[335] = SweepPair(13, KIND_GATED, 0xd2f2bd64, abi.encodeWithSelector(0xd2f2bd64, address(0)));
        pairs[336] = SweepPair(13, KIND_GATED, 0xf2fde38b, abi.encodeWithSelector(0xf2fde38b, address(0)));
        pairs[337] = SweepPair(
            13, KIND_GATED, 0xf4b34e17, abi.encodeWithSelector(
                0xf4b34e17, "", "", [address(0), address(0), address(0), address(0)], address(0), uint256(0), [uint256(0), uint256(0), uint256(0), uint256(0)], [uint16(0), uint16(0), uint16(0), uint16(0)], [uint16(0), uint16(0), uint16(0), uint16(0)]
            )
        );
        pairs[338] = SweepPair(13, KIND_GATED, 0xfc9d1243, abi.encodeWithSelector(0xfc9d1243));
        pairs[339] = SweepPair(13, KIND_GATED, 0xfdce6907, abi.encodeWithSelector(0xfdce6907, uint256(0), uint256(0)));
        pairs[340] = SweepPair(13, KIND_GATED, 0xfeb6195f, abi.encodeWithSelector(0xfeb6195f, uint256(0)));
        pairs[341] = SweepPair(0, KIND_GATED, 0x08b0b0c8, abi.encodeWithSelector(0x08b0b0c8, uint256(0)));
        pairs[342] = SweepPair(0, KIND_EXEMPT, 0x095ea7b3, abi.encodeWithSelector(0x095ea7b3, address(0), uint256(0)));
        pairs[343] = SweepPair(0, KIND_GATED, 0x0c9ad533, abi.encodeWithSelector(0x0c9ad533));
        pairs[344] = SweepPair(0, KIND_GATED, 0x14c6ec46, abi.encodeWithSelector(0x14c6ec46));
        pairs[345] = SweepPair(0, KIND_GATED, 0x165709d7, abi.encodeWithSelector(0x165709d7, address(0)));
        pairs[346] = SweepPair(0, KIND_GATED, 0x22611280, abi.encodeWithSelector(0x22611280));
        pairs[347] = SweepPair(
            0, KIND_EXEMPT, 0x23b872dd, abi.encodeWithSelector(
                0x23b872dd, address(0), address(0), uint256(0)
            )
        );
        pairs[348] = SweepPair(0, KIND_GATED, 0x24f13a76, abi.encodeWithSelector(0x24f13a76, uint256(0)));
        pairs[349] = SweepPair(0, KIND_GATED, 0x28882404, abi.encodeWithSelector(0x28882404, uint256(0)));
        pairs[350] = SweepPair(0, KIND_GATED, 0x3f4ba83a, abi.encodeWithSelector(0x3f4ba83a));
        pairs[351] = SweepPair(0, KIND_GATED, 0x40f29c6c, abi.encodeWithSelector(0x40f29c6c, address(0)));
        pairs[352] = SweepPair(0, KIND_GATED, 0x46a30f1d, abi.encodeWithSelector(0x46a30f1d, address(0)));
        pairs[353] = SweepPair(0, KIND_GATED, 0x48df1cbd, abi.encodeWithSelector(0x48df1cbd, ""));
        pairs[354] = SweepPair(0, KIND_GATED, 0x4b689820, abi.encodeWithSelector(0x4b689820, false));
        pairs[355] = SweepPair(0, KIND_GATED, 0x4f1ef286, abi.encodeWithSelector(0x4f1ef286, address(0), ""));
        pairs[356] = SweepPair(0, KIND_SEAM, 0x58bf3c7f, abi.encodeWithSelector(0x58bf3c7f, address(0)));
        pairs[357] = SweepPair(0, KIND_GATED, 0x59cd0ce3, abi.encodeWithSelector(0x59cd0ce3));
        pairs[358] = SweepPair(0, KIND_GATED, 0x5cd8a76b, abi.encodeWithSelector(0x5cd8a76b));
        pairs[359] = SweepPair(0, KIND_GATED, 0x5fd3fab4, abi.encodeWithSelector(0x5fd3fab4, address(0), uint256(0)));
        pairs[360] = SweepPair(
            0, KIND_SEAM, 0x61e65bbe, abi.encodeWithSelector(
                0x61e65bbe, address(0), address(0), address(0), uint256(0), uint256(0), uint8(0), "", address(0)
            )
        );
        pairs[361] = SweepPair(0, KIND_GATED, 0x666a0c84, abi.encodeWithSelector(0x666a0c84, address(0)));
        pairs[362] = SweepPair(0, KIND_GATED, 0x6e553f65, abi.encodeWithSelector(0x6e553f65, uint256(0), address(0)));
        pairs[363] = SweepPair(0, KIND_GATED, 0x6f331c8e, abi.encodeWithSelector(0x6f331c8e));
        pairs[364] = SweepPair(0, KIND_GATED, 0x715018a6, abi.encodeWithSelector(0x715018a6));
        pairs[365] = SweepPair(0, KIND_GATED, 0x7391ec91, abi.encodeWithSelector(0x7391ec91, address(0)));
        pairs[366] = SweepPair(0, KIND_GATED, 0x79ba5097, abi.encodeWithSelector(0x79ba5097));
        pairs[367] = SweepPair(0, KIND_GATED, 0x80ea3de1, abi.encodeWithSelector(0x80ea3de1, uint256(0)));
        pairs[368] = SweepPair(0, KIND_GATED, 0x8456cb59, abi.encodeWithSelector(0x8456cb59));
        pairs[369] = SweepPair(0, KIND_GATED, 0x867b9318, abi.encodeWithSelector(0x867b9318, false));
        pairs[370] = SweepPair(0, KIND_GATED, 0x8fc7a68e, abi.encodeWithSelector(0x8fc7a68e, address(0)));
        pairs[371] = SweepPair(0, KIND_GATED, 0x9280648c, abi.encodeWithSelector(0x9280648c, uint256(0)));
        pairs[372] = SweepPair(0, KIND_GATED, 0x94bf804d, abi.encodeWithSelector(0x94bf804d, uint256(0), address(0)));
        pairs[373] = SweepPair(0, KIND_GATED, 0x9ee679e8, abi.encodeWithSelector(0x9ee679e8, uint256(0)));
        pairs[374] = SweepPair(0, KIND_EXEMPT, 0xa9059cbb, abi.encodeWithSelector(0xa9059cbb, address(0), uint256(0)));
        pairs[375] = SweepPair(0, KIND_GATED, 0xaef18ae7, abi.encodeWithSelector(0xaef18ae7, address(0)));
        pairs[376] = SweepPair(0, KIND_GATED, 0xaf8d24fb, abi.encodeWithSelector(0xaf8d24fb));
        pairs[377] = SweepPair(0, KIND_GATED, 0xb309d6b7, abi.encodeWithSelector(0xb309d6b7));
        pairs[378] = SweepPair(
            0, KIND_GATED, 0xb460af94, abi.encodeWithSelector(
                0xb460af94, uint256(0), address(0), address(0)
            )
        );
        pairs[379] = SweepPair(
            0, KIND_GATED, 0xba087652, abi.encodeWithSelector(
                0xba087652, uint256(0), address(0), address(0)
            )
        );
        pairs[380] = SweepPair(0, KIND_GATED, 0xec78412e, abi.encodeWithSelector(0xec78412e, uint256(0)));
        pairs[381] = SweepPair(0, KIND_GATED, 0xece57ffb, abi.encodeWithSelector(0xece57ffb));
        pairs[382] = SweepPair(0, KIND_GATED, 0xf2fde38b, abi.encodeWithSelector(0xf2fde38b, address(0)));
        pairs[383] = SweepPair(0, KIND_GATED, 0xf55dd0fe, abi.encodeWithSelector(0xf55dd0fe, address(0), uint256(0)));
        pairs[384] = SweepPair(0, KIND_GATED, 0xf9bcd364, abi.encodeWithSelector(0xf9bcd364));
        pairs[385] = SweepPair(0, KIND_GATED, 0xfa45aa00, abi.encodeWithSelector(0xfa45aa00));
    }

    function test_sweepSelectorGate() public {
        address[CONTRACTS] memory targets = _sweepTargets();
        SweepPair[] memory pairs = _sweepPairs();
        uint256 gated;
        uint256 exempt;
        uint256 seams;
        uint256 ozGuarded;
        for (uint256 i; i < pairs.length; ++i) {
            SweepPair memory pair = pairs[i];
            address target = targets[pair.target];
            assertGt(target.code.length, 0, "SWEEP target has no code");
            vm.prank(sweepUnverified);
            (bool ok, bytes memory ret) = target.call(pair.data);
            if (pair.kind == KIND_GATED) {
                assertFalse(ok, "SWEEP gated call did not revert");
                assertTrue(
                    _revertSelector(ret) == IAllowlist.CallerNotAllowed.selector,
                    string.concat("SWEEP gated call reverted with the wrong selector: ", vm.toString(bytes32(pair.selector)))
                );
                assertEq(_revertCaller(ret), sweepUnverified, "SWEEP gated call named the wrong caller");
                ++gated;
            } else if (pair.kind == KIND_EXEMPT) {
                _requireNotGated(ok, ret, "SWEEP exempt call was gated");
                ++exempt;
            } else if (pair.kind == KIND_SEAM) {
                assertFalse(ok, "SWEEP bootstrap seam call succeeded for an unverified caller");
                _requireNotGated(ok, ret, "SWEEP bootstrap seam call was gated");
                ++seams;
            } else {
                ++ozGuarded;
            }
        }
        uint256 pairCount = gated + exempt;
        assertEq(pairCount, gated + EXEMPT_PAIRS, "SWEEP pairs != gated + exempt");
        assertEq(gated, GATED_PAIRS, "SWEEP gated pair count");
        assertEq(exempt, EXEMPT_PAIRS, "SWEEP exempt pair count");
        assertEq(seams, SEAM_PAIRS, "SWEEP bootstrap seam count");
        assertEq(ozGuarded, 0, "SWEEP unrecognized selector kinds");
        console.log(
            string.concat(
                "SWEEP contracts=",
                vm.toString(uint256(CONTRACTS)),
                " pairs=",
                vm.toString(pairCount),
                " gated=",
                vm.toString(gated),
                " exempt=",
                vm.toString(exempt),
                " selectorKinds=",
                vm.toString(uint256(SELECTOR_KINDS))
            )
        );
        console.log(string.concat("SWEEP seams=", vm.toString(seams), " ozGuarded=", vm.toString(ozGuarded)));
    }

    function _requireNotGated(bool ok, bytes memory ret, string memory label) internal pure {
        assertTrue(ok || _revertSelector(ret) != IAllowlist.CallerNotAllowed.selector, label);
    }

    function _revertSelector(bytes memory ret) internal pure returns (bytes4 selector) {
        if (ret.length < 4) return bytes4(0);
        assembly {
            selector := mload(add(ret, 32))
        }
    }

    function _revertCaller(bytes memory ret) internal pure returns (address account) {
        if (ret.length < 36) return address(0);
        assembly {
            account := mload(add(ret, 36))
        }
    }
}
